namespace: prod
name: myapp
replicaCount: 1

image:
  repository: registry.cn-beijing.aliyuncs.com/hatlonely/myapp
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets:
  name: hatlonely-pull-secrets

ingress:
  host: k8s.myapp.hatlonely.com
  secretName: k8s-secret

config:
  base: "{}"
  app: "{}"